### ISSUE TITLE
Latex equations convert error

### ISSUE THREAD

**Issue by feiyuxiaoThu** [roslovets/Live-Script-to-Markdown-Converter#4]
Thanks for your useful tool! And I found a tiny error about the latex equations in Live Script, all the equations were converted to img format. 
![screenshot](https://user-images.githubusercontent.com/33885664/157211068-d8d12d6c-ed66-451e-b5c7-6e0985d06260.png)

**Comment by roslovets** [comment]
Thinks! Sorry, I'm not sure what you mean.

**Comment by feiyuxiaoThu** [comment]
> Thinks! Sorry, I'm not sure what you mean.

ohh, I mean all the equations are converted into an img format like '<img>' not as the markdown equation format.

**Comment by roslovets** [comment]
Got it. This is designed in core library:
https://github.com/minoue-xx/livescript2markdown/blob/master/function/private/processEquations.m

If `Format='github'` (default) equations will be converted to images in order to show them on GitHub portal.

Try `Format='qiita'` ([hint](https://github.com/roslovets/Live-Script-to-Markdown-Converter#input-name-value-pair-arguments)). In this case Latex should be preserved.

**Comment by feiyuxiaoThu** [comment]
Thanks for your reply!
